// src/constants/pricing.ts
import type { Pricing } from '@/types/paintingEstimator';

export const DEFAULT_PRICING: Pricing = {
  laborRate: 60.00, // Adjusted for Richmond Hill market
  paintCoverage: 350,
  paintCosts: {
    behrDynastyMatte: 80,
    behrDynastyEggshell: 80,
    behrDynastySatin: 80,
    behrDynastySemiGloss: 80,
    behrMarqueeMatte: 70,
    behrMarqueeEggshell: 70,
    behrMarqueeSatin: 70,
    behrMarqueeSemiGloss: 70,
    behrPremiumPlusFlat: 60,
    behrPremiumPlusEggshell: 60,
    behrPremiumPlusSatin: 60,
    behrPremiumPlusSemiGloss: 60,
    behrPremiumPlusHiGloss: 60,
    behrUltraFlat: 65,
    behrUltraEggshell: 65,
    behrUltraSatin: 65,
    behrUltraSemiGloss: 65,
    benjaminMooreAdvanceSatin: 75,
    benjaminMooreAdvanceSemiGloss: 75,
    benjaminMooreAdvanceHighGloss: 75,
    benjaminMooreAuraMatte: 85,
    benjaminMooreAuraEggshell: 85,
    benjaminMooreAuraSatin: 85,
    benjaminMooreAuraSemiGloss: 85,
    benjaminMooreBenFlat: 50,
    benjaminMooreBenEggshell: 50,
    benjaminMooreBenSemiGloss: 50,
    benjaminMooreRegalFlat: 65,
    benjaminMooreRegalMatte: 65,
    benjaminMooreRegalEggshell: 65,
    benjaminMooreRegalPearl: 65,
    benjaminMooreRegalSemiGloss: 65,
    benjaminMooreScuffXMatte: 85,
    benjaminMooreScuffXEggshell: 85,
    benjaminMooreScuffXPearl: 85,
    benjaminMooreScuffXSemiGloss: 85,
    benjaminMooreUltraSpecFlat: 65,
    benjaminMooreUltraSpecLowSheenEggshell: 65,
    benjaminMooreUltraSpecEggshell: 65,
    benjaminMooreUltraSpecSatinPearl: 65,
    benjaminMooreUltraSpecSemiGloss: 65,
    sherwinWilliamsCaptivateFlat: 35,
    sherwinWilliamsCaptivateSatin: 35,
    sherwinWilliamsCaptivateSemiGloss: 35,
    sherwinWilliamsCashmereFlat: 50,
    sherwinWilliamsCashmereEggshell: 50,
    sherwinWilliamsCashmereLowLustre: 50,
    sherwinWilliamsCashmereMediumLustre: 50,
    sherwinWilliamsCashmerePearl: 50,
    sherwinWilliamsDurationMatte: 80,
    sherwinWilliamsDurationSatin: 80,
    sherwinWilliamsDurationSemiGloss: 80,
    sherwinWilliamsEmeraldFlat: 75,
    sherwinWilliamsEmeraldMatte: 75,
    sherwinWilliamsEmeraldSatin: 75,
    sherwinWilliamsEmeraldSemiGloss: 75,
    sherwinWilliamsHarmonyFlat: 50,
    sherwinWilliamsHarmonyEggshell: 50,
    sherwinWilliamsHarmonySemiGloss: 50,
    sherwinWilliamsProMar200Flat: 55,
    sherwinWilliamsProMar200Eggshell: 55,
    sherwinWilliamsProMar200LowSheenEggshell: 55,
    sherwinWilliamsProMar200LowGlossEggshell: 55,
    sherwinWilliamsProMar200SemiGloss: 55,
    sherwinWilliamsProMar200Gloss: 55,
    sherwinWilliamsProMar400Flat: 45,
    sherwinWilliamsProMar400Eggshell: 45,
    sherwinWilliamsProMar400LowSheen: 45,
    sherwinWilliamsProMar400SemiGloss: 45,
    sherwinWilliamsProMar400Gloss: 45,
    sherwinWilliamsSuperPaintFlat: 65,
    sherwinWilliamsSuperPaintSatin: 65,
    sherwinWilliamsSuperPaintVelvet: 65,
    sherwinWilliamsSuperPaintSemiGloss: 65,
},
  primerCost: 40,
  sprayUpcharge: 0.25,
  PROFIT_MARKUP: 2.0,
  TAX_RATE: 0.13, // HST for Ontario
  PRODUCTION_RATES: {
    wallPainting: 150,
    ceilingPainting: 150,
    popcornRemoval: 35,
    popcornRemovalAsbestos: 10,
    trims: 70,
    additional: 0,
  },
  ADDITIONAL_PAINT_USAGE: {
    wallPainting: 0,
    ceilingPainting: 0,
    popcornRemoval: 0,
    trims: 0.2,
    additional: 0,
  },
  HIGH_CEILING_TIERS: { '10': 0.1, '12': 0.2, '14+': 0.4 },
  WASTE_FACTOR: 1.1,
  COST_ASBESTOS_TEST: 500.00,
  MIN_JOB_FEE: 550.00,
  DISCOUNT_PERCENTAGE: 10,
  drywallCompoundCost: 20,
};