// src/constants/pricing.ts
import type { PricingConfig } from '@/types/paintingEstimator';

export const DEFAULT_PRICING: PricingConfig = {
  PROFIT_MARKUP: 2.0,
  TAX_RATE: 0.13,
  PAINTER_BURDENED_HOURLY_COST: 50.00,
  PAINT_COST_PER_GALLON: { good: 35, better: 60, best: 100 },
  SUPPLIES_PERCENTAGE: 0.15,
  PRODUCTION_RATES: {
    walls: 120,
    ceilings: 120,
    trim: 50,
    popcornRemoval: 50,
    interiorDoor: 1.0,
    closetDoor: 0.8,
    vanityDoor: 0.7,
    vanityDrawer: 0.5,
    cabinetDoor: 1.0,
    cabinetDrawer: 0.6,
  },
  ADDITIONAL_PAINT_USAGE: {
    trim: 0.2,
    interiorDoor: 20,
    closetDoor: 15,
    vanityDoor: 10,
    vanityDrawer: 5,
    cabinetDoor: 12,
    cabinetDrawer: 6,
  },
  BASE_PREP_HOURS_FIXED: 1.0,
  PREP_HOURS_PER_FLOOR_SQFT: 0.015,
  PREP_HOURS_PER_PERIMETER_LFT: 0.015,
  COST_MOLD_RESISTANT_PAINT_UPCHARGE: 15.00,
  COST_CROWN_MOLDING: 250.00,
  COST_FIREPLACE_MANTEL: 200.00,
  COST_STAIRWELL: 450.00,
  PREP_CONDITION_MULTIPLIERS: { good: 1.0, fair: 1.5, poor: 2.5 },
  TEXTURE_MULTIPLIERS: { smooth: 1.0, light: 1.3, heavy: 1.5 },
  EXTRA_COAT_MULTIPLIER: 0.5,
  HIGH_CEILING_MULTIPLIER: 1.20,
  COVERAGE_PER_GALLON: 350,
  PRIMER_COST_PER_GALLON: 35,
  INTERIOR_DOOR_MATERIAL_MULTIPLIERS: { Wood: 1.2, MDF: 1.0, Metal: 1.5 },
  CABINET_MATERIAL_MULTIPLIERS: { Wood: 1.0, Laminate: 1.3, Metal: 1.5 },
};